apiVersion: v1
kind: Service
metadata:
  name: counting
  namespace: default
  labels:
    app: counting
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
  selector:
    app: counting